version: "3.0"

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana
    command:
      - '--config=/etc/grafana/grafana.ini'
    ports:
      - "3001:3001"
    depends_on:
      - prometheus

  file-server:
    build: ./
    environment:
      - HTTP_SERVER_HOST=localhost
      - HTTP_SERVER_PROTOCOL=http
      - HTTP_SERVER_PORT=36000
      - HTTP_SERVER_TLS_PORT=37000
      - HTTP_SERVER_CERT_FILE=rest-api-file-server.crt
      - HTTP_SERVER_CERT_KEY=rest-api-file-server.key
      - HTTP_SERVER_READ_TIMEOUT_SECONDS=60
      - HTTP_SERVER_WRITE_TIMEOUT_SECONDS=60
      - HTTP_SERVER_TLS_ENABLED=False
      - FILE_SERVER_BASE_PATH=/Users/eertree_work/experiments/rest-api-file-server/test-data
    ports:
      - 8080:36000
    depends_on:
      - prometheus
      - node-exporter
      - grafana
